In [53]:
import numpy as np

In [54]:
data = np.array([1,2,3])
data.max()

3

In [55]:
# 创建
np.ones(3)

array([1., 1., 1.])

In [56]:
np.zeros(3)

array([0., 0., 0.])

In [57]:
np.random.random(3)

array([0.34876344, 0.42589274, 0.79054878])

In [58]:
np.random.randint(10)

6

In [59]:
# 算术运算
data = np.array([1,2])
ones = np.ones(2)
data + ones

array([2., 3.])

In [60]:
data - ones

array([0., 1.])

In [61]:
data * ones

array([1., 2.])

In [62]:
data / ones

array([1., 2.])

In [63]:
data * 1.6

array([1.6, 3.2])

In [64]:
# 切片
data = np.array([1,2,3,4,5,6,])
data

array([1, 2, 3, 4, 5, 6])

In [66]:
data[0]

1

In [67]:
data[1]

2

In [68]:
data[-1]

6

In [69]:
data[0:2]

array([1, 2])

In [71]:
data[1:]

array([2, 3, 4, 5, 6])

聚合函数

In [83]:
print(f"data.max():{data.max()}")
print(f"data.min():{data.min()}")
print(f"data.sum():{data.sum()}")
print(f"data.mean():{data.mean()}")
print(f"data.prod():{data.prod()}")
print(f"data.std():{data.std()}")
print(f"data.data:{data.data}")
print(f"data.dtype:{data.dtype}")
print(f"data.shape:{data.shape}")
print(f"data.size:{data.size}")
print(f"data.base:{data.base}")

data.max():6
data.min():1
data.sum():21
data.mean():3.5
data.prod():720
data.std():1.707825127659933
data.data:<memory at 0x0000018C341A6DC0>
data.dtype:int32
data.shape:(6,)
data.size:6
data.base:None


矩阵

In [85]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [86]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [87]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [88]:
np.random.random((3,2))

array([[0.69372861, 0.20247339],
       [0.19518031, 0.33649213],
       [0.1763275 , 0.6894015 ]])

In [91]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [89]:
np.zeros(6).reshape((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

矩阵运算

In [102]:
data1 = np.array([[1,2],[3,4]])
data2 = np.array([[1,1],[1,1]])
data1 + data2

array([[2, 3],
       [4, 5]])

In [103]:
data1 - data2

array([[0, 1],
       [2, 3]])

In [104]:
data1 * data2

array([[1, 2],
       [3, 4]])

In [105]:
data1 / data2

array([[1., 2.],
       [3., 4.]])

In [96]:
data1 = np.ones(shape=(3,2))
data2 = np.ones(shape=(1,2))
data1 + data2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [107]:
# 点积
data13 = np.array([n for n in range(1,4)])
data13

array([1, 2, 3])

In [157]:
powers_of_ten = np.array([10**n for n in range(6)]).reshape((3,2))
powers_of_ten

array([[     1,     10],
       [   100,   1000],
       [ 10000, 100000]])

In [112]:
data13.dot(powers_of_ten)

array([ 30201, 302010])

矩阵的切片和聚合

In [137]:
data32 = np.arange(1,7).reshape((3,2))
data32

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
data32[0,1]

2

In [125]:
data32[1]  # = data32[1,:]

array([3, 4])

In [127]:
data32[1,0:1]

array([3])

In [128]:
data32[1:3]

array([[3, 4],
       [5, 6]])

In [126]:
data32[:,0]

array([1, 3, 5])

In [129]:
data32[0:2,0]

array([1, 3])

In [130]:
data32.max()

6

In [131]:
data32.min()

1

In [132]:
data32.sum()

21

In [133]:
data32.max(axis=0)

array([5, 6])

In [134]:
data32.min(axis=1)

array([1, 3, 5])

矩阵的转置和重构

In [135]:
data32.T

array([[1, 3, 5],
       [2, 4, 6]])

In [144]:
data32.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [145]:
data32.reshape(2,3)  # = data32.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
data32.reshape(3,1,2)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [152]:
np.array([[[1,2],[3,4]],
          [[5,6],[7,8]],
          [[7,8],[9,10]]]).shape

(3, 2, 2)

In [153]:
np.ones(shape=(4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

公式应用

MeanSquareError = 1/n sum(i=1-n) (Y_prediction_i - Y_i)**2

In [155]:
n = 3
predictions = np.ones(3)
labels = np.arange(1,4)
error = (1/n) * np.sum(np.square(predictions - labels))
error

1.6666666666666665

np 表示日常数据
- 表格
- 音频和实际序列
- 图像
- 语言

查看文章

https://mp.weixin.qq.com/s/dbSVAhIK6gDyLlaSPx9kOw